//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace item31
{
    using System;
    using System.Collections.Generic;
    
    public partial class excel
    {
        public double ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> ELO { get; set; }
        public Nullable<double> Seed { get; set; }
    }
}
